import Modal from './Modal';
import { formatCurrency, formatDate } from '../utils/helpers';
import { Receipt } from 'lucide-react';

export default function ReceiptModal({ open, onClose, payment }) {
  if (!payment) return null;

  return (
    <Modal open={open} onClose={onClose} title="Payment Receipt">
      <div className="space-y-5">
        <div className="flex items-center justify-center">
          <div className="bg-primary-50 p-4 rounded-full">
            <Receipt size={32} className="text-primary-600" />
          </div>
        </div>

        <div className="text-center">
          <h3 className="text-lg font-semibold text-surface-900">SocietyHub</h3>
          <p className="text-sm text-surface-500">Green Valley Society</p>
        </div>

        <div className="border-t border-b border-dashed border-surface-200 py-4 space-y-3 text-sm">
          <div className="flex justify-between">
            <span className="text-surface-500">Receipt No</span>
            <span className="font-medium text-surface-700">{payment.id}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-surface-500">Month</span>
            <span className="font-medium text-surface-700">{payment.month}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-surface-500">Amount</span>
            <span className="font-medium text-surface-700">{formatCurrency(payment.amount)}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-surface-500">Payment Date</span>
            <span className="font-medium text-surface-700">{formatDate(payment.date)}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-surface-500">Transaction ID</span>
            <span className="font-medium text-surface-700">{payment.transactionId}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-surface-500">Status</span>
            <span className="font-medium text-emerald-600">{payment.status}</span>
          </div>
        </div>

        <p className="text-xs text-center text-surface-400">
          This is a demo receipt generated by SocietyHub. Not a valid financial document.
        </p>
      </div>
    </Modal>
  );
}
