import Modal from './Modal';
import { formatCurrency, formatDate } from '../utils/helpers';
import { Receipt } from 'lucide-react';

export default function ReceiptModal({ open, onClose, payment }) {
  if (!payment) return null;

  return (
    <Modal open={open} onClose={onClose} title="Payment Receipt">
      <div className="space-y-6 py-2">
        <div className="flex flex-col items-center justify-center space-y-4">
          <div className="bg-primary-50 p-4 rounded-full border border-primary-100 shadow-sm">
            <Receipt size={32} className="text-primary-600" />
          </div>
          <div className="text-center">
            <h3 className="text-xl font-bold text-surface-900 tracking-tight">SocietyHub</h3>
            <p className="text-sm font-medium text-surface-500">Green Valley Society</p>
          </div>
        </div>

        <div className="bg-surface-50 rounded-2xl p-5 border border-surface-200 w-full text-sm space-y-3">
          <div className="flex justify-between items-center">
            <span className="text-[13px] font-bold text-surface-500 uppercase tracking-wide">Receipt No</span>
            <span className="font-mono text-sm font-bold text-surface-700">{payment.id}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-[13px] font-bold text-surface-500 uppercase tracking-wide">Month</span>
            <span className="font-bold text-surface-900">{payment.month}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-[13px] font-bold text-surface-500 uppercase tracking-wide">Amount</span>
            <span className="font-bold text-surface-900">{formatCurrency(payment.amount)}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-[13px] font-bold text-surface-500 uppercase tracking-wide">Payment Date</span>
            <span className="font-bold text-surface-700">{formatDate(payment.date)}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-[13px] font-bold text-surface-500 uppercase tracking-wide">Transaction ID</span>
            <span className="font-mono text-sm font-bold text-surface-700">{payment.transactionId}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-[13px] font-bold text-surface-500 uppercase tracking-wide">Status</span>
            <span className="bg-emerald-50 text-emerald-700 border border-emerald-200/60 px-2 py-0.5 rounded-md text-[11px] font-bold uppercase tracking-wide">{payment.status}</span>
          </div>
        </div>

        <p className="text-[11px] font-bold text-surface-400 text-center uppercase tracking-wider">
          Demo receipt generated by SocietyHub. Not a valid financial document.
        </p>
      </div>
    </Modal>
  );
}
