import Modal from './Modal';
import { formatCurrency, formatDate } from '../utils/helpers';
import { Receipt } from 'lucide-react';

export default function ReceiptModal({ open, onClose, payment }) {
  if (!payment) return null;

  return (
    <Modal open={open} onClose={onClose} title="Payment Receipt">
      <div className="space-y-6 mt-2">
        <div className="flex flex-col items-center justify-center space-y-3">
          <div className="bg-primary-50 p-3.5 rounded-2xl border border-primary-100 shadow-sm">
            <Receipt size={24} className="text-primary-600" />
          </div>
          <div className="text-center">
            <h3 className="text-lg font-bold text-surface-900 tracking-tight">SocietyHub</h3>
            <p className="text-[11px] font-semibold text-surface-400 uppercase tracking-widest mt-0.5">Green Valley Society</p>
          </div>
        </div>

        <div className="bg-surface-50 rounded-xl p-5 border border-surface-200/80 w-full text-sm space-y-3 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-20 h-20 bg-primary-100/50 rounded-bl-full pointer-events-none" />
          
          <div className="flex justify-between items-center relative z-10">
            <span className="text-[11px] font-bold text-surface-500 uppercase tracking-widest">Receipt No</span>
            <span className="font-mono text-[11px] font-semibold text-surface-700 bg-white px-2 py-0.5 rounded border border-surface-200">{payment.id}</span>
          </div>
          <div className="flex justify-between items-center relative z-10">
            <span className="text-[11px] font-bold text-surface-500 uppercase tracking-widest">Month</span>
            <span className="font-bold text-surface-900">{payment.month}</span>
          </div>
          <div className="flex justify-between items-center relative z-10">
            <span className="text-[11px] font-bold text-surface-500 uppercase tracking-widest">Amount</span>
            <span className="font-bold text-surface-900">{formatCurrency(payment.amount)}</span>
          </div>
          <div className="flex justify-between items-center relative z-10">
            <span className="text-[11px] font-bold text-surface-500 uppercase tracking-widest">Payment Date</span>
            <span className="font-semibold text-surface-700">{formatDate(payment.date)}</span>
          </div>
          <div className="flex justify-between items-center relative z-10">
            <span className="text-[11px] font-bold text-surface-500 uppercase tracking-widest">Transaction ID</span>
            <span className="font-mono text-[11px] font-semibold text-surface-700 bg-white px-2 py-0.5 rounded border border-surface-200">{payment.transactionId}</span>
          </div>
          <div className="flex justify-between items-center pt-2 border-t border-surface-200 relative z-10">
            <span className="text-[11px] font-bold text-surface-500 uppercase tracking-widest">Status</span>
            <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wide bg-emerald-50 text-emerald-700 border border-emerald-200/60">
              {payment.status}
            </span>
          </div>
        </div>

        <div className="text-center pt-2">
          <p className="text-[10px] font-bold text-surface-400 uppercase tracking-widest leading-relaxed">
            Demo receipt generated by SocietyHub.<br/>Not a valid financial document.
          </p>
        </div>
      </div>
    </Modal>
  );
}
